### PR TITLE
Publish GitHub Page with GitHub Action

### PR DESCRIPTION
**Pull request by focaaby**
Use #20 `makefile` 
1. Generate the HTML assets and deploy them to the [GitHub Page](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)[1].
    * Here is the demo URL: https://focaaby.github.io/lkmpg/index.html
2. Publish the `html` directory as release HTML assets.
    * Demo download URL: https://github.com/focaaby/lkmpg/releases/download/latest/lkmpg-html.tar.gz

References:
1. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

### CODE REVIEW

**Comment by jserv** [comment]
> Here is the demo URL: https://focaaby.github.io/lkmpg/index.html

TikZ graph was not rendered correctly. @fennecJ, can you give a hint?

**Comment by fennecJ** [comment]
I tryied to use @focaaby 's action script, and my TikZ graph was not rendered correctly, either.
I have checked the version of the tool we used and don't find any problem currently.

As I mentioned in #27 , [xu-cheng/texlive-action](https://github.com/xu-cheng/texlive-action) worked well and rendered the page correctly.
Consider switch to [xu-cheng/texlive-action](https://github.com/xu-cheng/texlive-action) instead of texlive/texlive ?

**Comment by Hsins** [comment]
Umm...

- Workflows in GitHub Actions/GitLab CI/Azure Pipeline... are series of tasks running on the docker container.
- Docker containers are instances of given docker image.

They are not the same thing. Switching from workflows to workflows is just switching the environments that other defined, why don't we just created the environment for us?

**Comment by fennecJ** [comment]
@Hsins 
Sorry I didn't notice that you have built up a docker image when I comment then.
And I tried your [docker image](https://github.com/TeXtw/docker-lkmpg), it worked well.
I agree that we should just create the environment for us.

**Review by jserv — CHANGES_REQUESTED** [review]
Read this carefully: https://chris.beams.io/posts/git-commit/
* Wrap the body at 72 characters

Don't use markdown syntax inside git commit message.

**Comment by jserv** [comment]
For the sake of naming consistency, rename `.github/workflows/generate_pdf.yml` to `.github/workflows/generate_docs.yml` which generates PDF and HTML accordinly.

**Comment by jserv** [comment]
The message is too long:
> Add a new Github Action to publish to the GitHub page. Use https://github.com/TeXtw/docker-lkmpg image for reproducibility.

Wrap the body at 72 characters.

**Comment by jserv** [comment]
Thank @focaaby for contributing!

**Comment by jserv** [comment]
I was not aware of the HTML generation on GitHub Pages. Here are the configurations:
GitHub Pages

@focaaby, how should I make changes?

**Comment by fennecJ** [comment]
For the sake of naming consistency, both 2  script files should be ended with `.yml` either `.yaml` .
According to [yaml.org](https://yaml.org/faq.html)
>### Is there an official extension for YAML files?
>Please use ".yaml" when possible.

It seems .yaml is better choise.

**Comment by fennecJ** [comment]
@jserv 
I can see the page in [https://sysprog21.github.io/lkmpg](https://sysprog21.github.io/lkmpg) now.
Maybe it's caused by cache?
Try using ctrl + F5 to refresh the page.

**Comment by jserv** [comment]
> I can see the page in https://sysprog21.github.io/lkmpg now.
> Maybe it's caused by cache?

It works for me now. Thanks!

**Pull request merged**
