### PR TITLE
Convey secure boot specific considerations

### PR DESCRIPTION
**Pull request by bbyykk**
I create a topic branch and hope this time could go more smoothly

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
You should rebase the latest `master` branch and squash the commits using `git rebase -i`.

**Comment by jserv** [comment]
@bbyykk, You don't have to close this pull request. Instead, use `git push --force`.

**Review by linD026 — APPROVED** [review]
Looks good to me.

**Comment by jserv** [comment]
Thank @bbyykk for contributing. Next time, you shall practice git skills.

**Pull request merged**
