### PR TITLE
WIP: Dockerized pdf build in Github Actions

### PR DESCRIPTION
**Pull request by ekangmonyet**
Build and release a pdf after every push to master using texlive/texlive docker image.
This PR is meant to be scope limited to serve as a foundation for #15 and #25.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Improve the git commit message.
See https://chris.beams.io/posts/git-commit/

**Comment by ekangmonyet** [comment]
Fixing issue when replacing the release asset

**Review by jserv — CHANGES_REQUESTED** [review]
Fillename ".github/workflows/main.yml" is not so meaningful. Revise it.

**Comment by jserv** [comment]
Change filename from `release_pdf_github.yml` to `generate_docs.yml` or `generate_pdf.yml`.

**Comment by jserv** [comment]
Thank @ekangmonyet for contributing! I amended the commit message slightly.

**Pull request merged**
