### PR TITLE
Fix command style

### PR DESCRIPTION
**Pull request by 2011eric**
Little changes regarding the use of `sudo`.

### CODE REVIEW

**Comment by jserv** [comment]
I would like to enforce the assumption of using as a non-root user. That is, it is necessary to specify `sudo` for the essential commands such as `insmod` and `rmmod`. In addition, most command prompts should start with `$` (dollar sign).

**Comment by 2011eric** [comment]
I've specified `sudo` command and replaced `#` with `$`.

**Review by jserv — CHANGES_REQUESTED** [review]
Rebase the latest `master` branch.

**Comment by jserv** [comment]
You should manipulate with not only this block but also other starting with `\begin{verbatim}`. e.g.,
```
\begin{verbatim}
# cat /proc/helloworld
HelloWorld!
\end{verbatim}
```

Change the leading `#` into `$`.

**Comment by jserv** [comment]
After rebasing, you should force push.

**Comment by 2011eric** [comment]
I rebased, added a commit , and force pushed. Will that be a problem?

**Comment by jserv** [comment]
> I rebased, added a commit , and force pushed. Will that be a problem?

You only force push your own branch rather than master branch, which does not hurt anything.

**Comment by jserv** [comment]
Use `git rebase -i` to drop commit "Add header and footer"

**Comment by jserv** [comment]
Thank @2011eric for contributing. I amended the commit message for precise wording.

**Pull request merged**
